apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc-np
spec:
  selector:
    app: nginx-multi
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      nodePort: 30001
    - name: multitool
      protocol: TCP
      port: 8090
      nodePort: 30002
  type: NodePort