apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
# namespace: web
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 1Gi